services:
  iptv-failover:
    build: .
    container_name: iptv-failover
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./input:/app/input                # Your M3U files live here
